CREATE DATABASE STREAMING;

USE DATABASE STREAMING;

CREATE TABLE CADASTRO (
    IDCADASTRO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    EMAIL VARCHAR(40) NOT NULL,
    SENHA INT NOT NULL,
    PLANO VARCHAR (10)
);

CREATE TABLE RELATORIO_DEV (
    IDRELATORIO_DEV INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    BUGS VARCHAR (50),
    CUSTOMIZACAO VARCHAR (50),
    INOVACAO VARCHAR (50)
);

CREATE TABLE FORMA_PAGAMENTO (
    IDFORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FORMA_PAGAMENTO VARCHAR (15),
    BANDEIRA VARCHAR (15),
    PRAZO_VENCIMENTO DATE
);

CREATE TABLE FILME (
    IDFILME INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR (30),
    CLASSIFICACAO VARCHAR(30),
    PRODUTORA VARCHAR (30),
    DURACAO INT,
    IDADE INT
);

CREATE TABLE SERIE (
    IDSERIE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR (30),
    CLASSIFICACAO VARCHAR(30),
    TEMPORADAS INT,
    PRODUTORA VARCHAR (30),
    DURACAO INT,
    IDADE INT   
);



INSERT INTO CADASTRO VALUES
(1,'GABRIEL VIANA', '04.09.2022', 'GABRIELVIANA.FCB9@GMAIL.COM', 123456, 'GOLD');
INSERT INTO CADASTRO VALUES
(2,'LUCAS SOARES', '13.11.2022', 'LUCASOARES123456@GMAIL.COM', 123456, 'GOLD');
INSERT INTO CADASTRO VALUES
(3,'JOSE GOMES', '05.05.2022', 'JOSEGOMESPESSOAL@GMAIL.COM', 123456, 'SILVER');

INSERT INTO RELATORIO_DEV VALUES
(NULL,13,27,1);

INSERT INTO FORMA_PAGAMENTO VALUES
(NULL, 'CARTAO','VISA','25.12.2022');
INSERT INTO FORMA_PAGAMENTO VALUES
(NULL, 'CARTAO','MASTER','01.02.2023');
INSERT INTO FORMA_PAGAMENTO VALUES
(NULL, 'DINHEIRO','NULL','03.03.2022');

INSERT INTO FILME VALUES
(NULL,'AS BRANQUELAS','COMEDIA','PROMO STUDIO',130,'14');
INSERT INTO FILME VALUES
(NULL,'JACKASS','COMEDIA','PARAMOUNT',200,'18');
INSERT INTO FILME VALUES
(NULL,'O EXORCISTA','TERROR','PROMO STUDIO',145,'18');

INSERT INTO SERIE VALUES
(NULL,'JEFFREY DAHMER','TERROR',7,'PARAMOUNT',2437,18);
INSERT INTO SERIE VALUES
(NULL,'TURNO MACABRO','COMEDIA',5,'DIVINE PRODUCTIONS',2210,16);
INSERT INTO SERIE VALUES
(NULL,'NARCOS','SUSPENSE',11,'PARAMOUNT',1455,18);

DROP TABLE CADASTRO;
DROP TABLE RELATORIO_DEV;
DROP TABLE FORMA_PAGAMENTO;
DROP TABLE FILME;
DROP TABLE SERIE; 


DELETE FROM NOME_COMPLETO;
DELETE FROM BUGS;
DELETE FROM BANDEIRA;
DELETE FROM FILME;
DELETE FROM SERIE;

ALTER TABLE FILME
MODIFY CLASSIFICACAO VARCHAR(30);

ALTER TABLE SERIE
MODIFY CLASSIFICACAO VARCHAR(30);


/*Filtre os prazos de vencimento da tabela de forma de pagamento;
/*Filtre os filmes e séries;
/*A produtora Paramount produziu quais filmes e séries? Selecione todos os dados.
