/* INSERTS EM TABELAS */

INSERT INTO PRODUTO VALUES 
(1, 'SHAMPOO','LIMPEZA', 1, '10.50');

INSERT INTO PRODUTO VALUES 
(2, 'CARRAPATICIDA','LIMPEZA', 1, '15.00');

INSERT INTO PRODUTO VALUES 
(3, 'PERFUME','LIMPEZA', 1, '10.50');

INSERT INTO PRODUTO VALUES 
(4, 'TALCO','LIMPEZA', 1, '5.50');
==
INSERT INTO CLIENTE VALUES 
('1', 'ALEXANDER', 'ALEXANDER.DORE@HOTMAIL.COM');

INSERT INTO CLIENTE VALUES 
('2', 'LUCIANO', 'LUCIANO.FILHO@HOTMAIL.COM');

INSERT INTO CLIENTE VALUES 
('3', 'MATHEUS', 'MATHEUS.HENRIQUE@HOTMAIL.COM');

INSERT INTO CLIENTE VALUES 
('4', 'JOSE GOMES', 'JOSE.GOMES@HOTMAIL.COM');
==
INSERT INTO PET VALUES 
('1','MIKE','POODLE','PEQUENO','10.08.2009','1');

INSERT INTO PET VALUES 
('2','PRETA','VIRALATA','MEDIO','02.07.2020','2');

INSERT INTO PET VALUES 
('3','FLOCK','LABRADOR','MEDIO','24.04.2020','3');

INSERT INTO PET VALUES 
('4','THOR','GOLDEN','GRANDE','21.06.2020','3');

=
INSERT INTO PRONTUARIO VALUES 
('1','FEBRE','38.5','15');

INSERT INTO PRONTUARIO VALUES 
('2','FEBRE','39.9','22');

INSERT INTO PRONTUARIO VALUES 
('3','DOR DE BARRIGA','34.0','29');

INSERT INTO PRONTUARIO VALUES 
('4','FRAQUEZA','35.7','50');
==
INSERT INTO FUNCIONARIO VALUES
('1','GABRIEL VIANA',69822563211,'1250.56','M','1','TOSADOR','3.2');

INSERT INTO FUNCIONARIO VALUES
('2','MARCIO ALEX',02216987699,'1392.12','M',1,'VETERINARIO',1.5);

INSERT INTO FUNCIONARIO VALUES
('3','MATHEUS LEMOS',44920366978,'2250.44','M',2,'AUXILIAR MEDICO',0.5);

INSERT INTO FUNCIONARIO VALUES
('4','GABRIEL BASTOS',69580311102,'4565.09','M',2,'MEDICO GERAL',0.7);
==
INSERT INTO CLIENTE_PET VALUES 
(1, 1, 1);

INSERT INTO CLIENTE_PET VALUES 
(2, 2, 2);

INSERT INTO CLIENTE_PET VALUES 
(3, 3, 3);

INSERT INTO CLIENTE_PET VALUES 
(4, 4, 4);
=

INSERT INTO FORMA_PAGAMENTO VALUES 
(1, 'A VISTA');

INSERT INTO FORMA_PAGAMENTO VALUES 
(2, 'DEBITO');

INSERT INTO FORMA_PAGAMENTO VALUES 
(3, 'CREDITO');

INSERT INTO FORMA_PAGAMENTO VALUES 
(4, 'CHEQUE');
=

INSERT INTO PRODUTO_VENDA VALUES
(1,1,1);

INSERT INTO PRODUTO_VENDA VALUES
(2,2,2);

INSERT INTO PRODUTO_VENDA VALUES
(3,3,3);

INSERT INTO PRODUTO_VENDA VALUES
(4,4,4);
=

INSERT INTO VENDA VALUES
(1,1,1,1);

INSERT INTO VENDA VALUES
(2,2,2,2);

INSERT INTO VENDA VALUES
(3,3,3,3);

INSERT INTO VENDA VALUES
(4,4,4,4);

/* ATIVIDADE */

1. Visualizar todos os dados e colunas de cada uma das tabelas;
SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE_PET;

SELECT * FROM FORMA_PAGAMENTO;

SELECT * FROM FUNCIONARIO;

SELECT * FROM PET;

SELECT * FROM PRODUTO;

SELECT * FROM PRODUTO_VENDA;

SELECT * FROM PRONTUARIO;

SELECT * FROM VENDA;


2. Contar quantos registros tem em cada tabela;

SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE_PET;

SELECT COUNT(*) FROM FORMA_PAGAMENTO;

SELECT COUNT(*) FROM FUNCIONARIO;

SELECT COUNT(*) FROM PET;

SELECT COUNT(*) FROM PRODUTO;

SELECT COUNT(*) FROM PRODUTO_VENDA;

SELECT COUNT(*) FROM PRONTUARIO;

SELECT COUNT(*) FROM VENDA;
=
3. Informar quantos valores distintos existem para a tabela produtos na coluna preço;
SELECT DISTINCT COUNT(*)VALOR FROM PRODUTO;

=
4. Selecionar quais valores distintos existem para a tabela produtos na coluna preço;
SELECT DISTINCT VALOR FROM PRODUTO;
=
5. Informar quantos valores distintos existem para a tabela pet na coluna porte;
SELECT DISTINCT COUNT(*)PORTE FROM PET;

=
6. Selecionar quais valores distintos existem para a tabela pet na coluna porte;
SELECT DISTINC PORTE FROM PET; 

=
7. SELECT * FROM PRONTUARIO WHERE ID_PRONTUARIO IS NULL;
=
8. SELECT * FROM FUNCIONARIO WHERE ESPECIALIDADE IN ('VETERINARIO','ATENDENTE');
=
9. SELECT ID FROM FORMA_PAGAMENTO WHERE DESCRICAO='PIX'
=
10. Listar os 5 produtos de maior valor;
SELECT * FROM PRODUTOS ORDER BY VALOR ASC;
=
11. Listar os 5 produtos de menor valor;
SELECT * FROM PRODUTOS ORDER BY VALOR DESC;
=
12. Listar os funcionários ordenados pelo nome;
SELECT * FROM FUNCIONARIO ORDER BY NOME ASC;
